name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: install node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: build dist
        run: |
          npm install -g yarn
          yarn install
          yarn build
      - name: upload files to OSS
        id: upload_to_oss
        uses: royalrover/workbench-oss@master
        with:
          ACCESS_KEY: ${{ secrets.ACCESS_KEY_ID }}
          ACCESS_SECRET: ${{ secrets.ACCESS_KEY_SECRET }}
          OSS_BUCKET: lzc-weather-report
          OSS_REGION: oss-cn-beijing
          UPLOAD_PATH: ./build
          OSS_PATH: /